# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


gimbal_roll_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_roll_joint
  pid: {p: 0.3, i: 0.0, d: 0.0001}

gimbal_pitch_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_pitch_joint
  pid: {p: 0.3, i: 0.0, d: 0.0001}

gimbal_yaw_controller:
  type: effort_controllers/JointPositionController
  joint: gimbal_yaw_joint
  pid: {p: 0.3, i: 0.0, d: 0.0001}